MPR -- miles per gallon 
- 1 mile is 1.6 km
- 1 gallon  is 3.7 km

In [170]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings ("ignore")

In [171]:
df=sns.load_dataset('mpg')
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [172]:
df.drop("name",axis=1, inplace=True)

In [173]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,usa
1,15.0,8,350.0,165.0,3693,11.5,70,usa
2,18.0,8,318.0,150.0,3436,11.0,70,usa
3,16.0,8,304.0,150.0,3433,12.0,70,usa
4,17.0,8,302.0,140.0,3449,10.5,70,usa

In [174]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
dtypes: float64(4), int64(3), object(1)
memory usage: 25.0+ KB

In [175]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin           object
dtype: object

In [176]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [177]:
#  Since we have not done outlier treatment, then better idea be to replace the median value

In [178]:
df['horsepower'].median()

93.5

In [179]:
df['horsepower']=df['horsepower'].fillna(df['horsepower'].median())
df['horsepower']

0      130.0
1      165.0
2      150.0
3      150.0
4      140.0
       ...
393     86.0
394     52.0
395     84.0
396     79.0
397     82.0
Name: horsepower, Length: 398, dtype: float64

In [180]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [181]:
df['origin'].value_counts()

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

### Data encoding

In [182]:
df["origin"]=df["origin"].map({"usa":1,"japan":2,"europe":3})

In [183]:
df["origin"]=df["origin"].astype(int)
df["origin"]

0      1
1      1
2      1
3      1
4      1
      ..
393    1
394    3
395    1
396    1
397    1
Name: origin, Length: 398, dtype: int64

In [184]:
# Seprtae into x and y

In [185]:
x=df.drop('mpg',axis=1)
y=df['mpg']

In [186]:
x

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,8,307.0,130.0,3504,12.0,70,1
1,8,350.0,165.0,3693,11.5,70,1
2,8,318.0,150.0,3436,11.0,70,1
3,8,304.0,150.0,3433,12.0,70,1
4,8,302.0,140.0,3449,10.5,70,1
...,...,...,...,...,...,...,...
393,4,140.0,86.0,2790,15.6,82,1
394,4,97.0,52.0,2130,24.6,82,3
395,4,135.0,84.0,2295,11.6,82,1
396,4,120.0,79.0,2625,18.6,82,1
397,4,119.0,82.0,2720,19.4,82,1

In [187]:
y

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

### train test split

In [188]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=0.3, random_state=1)

In [189]:
x_train.shape

(278, 7)

### Simple Linear Regression

In [190]:
from sklearn.linear_model import LinearRegression
Regression_model=LinearRegression()

In [191]:
Regression_model

LinearRegression()

In [192]:
Regression_model.fit(x_train, y_train)

LinearRegression()

In [193]:
Regression_model.coef_

array([-0.31761423,  0.02623748, -0.01827076, -0.00748775,  0.05040673,
        0.84709514,  1.51909584])

In [194]:
for i, col_name in enumerate(x_train.columns):
    print(f"The coefficent for {col_name} is {Regression_model.coef_[i]}")

The coefficent for cylinders is -0.31761423027993324
The coefficent for displacement is 0.026237482599078946
The coefficent for horsepower is -0.018270764913124498
The coefficent for weight is -0.007487750398361902
The coefficent for acceleration is 0.05040673461971465
The coefficent for model_year is 0.8470951427061373
The coefficent for origin is 1.5190958387975053

In [195]:
## Onservation
# Coefficients ar relatively smaller, if one independent variable
# there will be not much difference in preediction
# This is sometime called as smoother model

# This feature might not be contributing in model training

In [196]:
from sklearn.metrics import r2_score

y_pred_linear=Regression_model.predict(x_test)
r2_linear=r2_score(y_test, y_pred_linear)
print(f"The r squre of linear regression {r2_linear}")

The r squre of linear regression 0.8348001123742284

### Regularised model

##  Ridge Regression

In [197]:
from sklearn.linear_model import Ridge
ridge_regression_model=Ridge(alpha=0.1)
ridge_regression_model
# In practical implemantation lambda is alpha

Ridge(alpha=0.1)

In [198]:
ridge_regression_model.fit(x_train, y_train)

Ridge(alpha=0.1)

In [199]:
for i, col_name in enumerate(x_train.columns):
    print(f"The coefficent for {col_name} is {ridge_regression_model.coef_[i]}")

The coefficent for cylinders is -0.317003210100659
The coefficent for displacement is 0.026213249757982997
The coefficent for horsepower is -0.01826325248144963
The coefficent for weight is -0.0074873260502130775
The coefficent for acceleration is 0.05036896947442412
The coefficent for model_year is 0.8470062938903169
The coefficent for origin is 1.517452828565388

In [200]:
# for ridge regression evaluation

y_pred_ridge=ridge_regression_model.predict(x_test)
r2_ridge=r2_score(y_test, y_pred_ridge)
print(f"The r squre of ridge regression {r2_ridge}")

The r squre of ridge regression 0.8348084889168355

In [201]:
#We dont see much variation in coeff of ridge regression as compare to linear regression

## Lasso

In [202]:
from sklearn.linear_model import Lasso

In [203]:
lasso_regression_model=Lasso(alpha=0.5)

In [204]:
lasso_regression_model

Lasso(alpha=0.5)

In [205]:
lasso_regression_model.fit(x_train, y_train)

Lasso(alpha=0.5)

In [206]:
for i, col_name in enumerate(x_train.columns):
    print(f"The coefficent for {col_name} is {lasso_regression_model.coef_[i]}")

The coefficent for cylinders is -0.0
The coefficent for displacement is 0.006208198888300369
The coefficent for horsepower is -0.01105838298716959
The coefficent for weight is -0.006982673168023089
The coefficent for acceleration is 0.0
The coefficent for model_year is 0.744654952003819
The coefficent for origin is 0.0

In [207]:
## Three features coefficient is 0, lasso helps in features selction

In [208]:
y_pred_lasso=lasso_regression_model.predict(x_test)
r2_lasso=r2_score(y_test, y_pred_lasso)
print(f"The r square of lasso regression {r2_lasso}")

The r square of lasso regression 0.8277934716635555

## Elastic Net

In [209]:
from sklearn.linear_model import ElasticNet
elastic_net_model=ElasticNet(alpha=1, l1_ratio=0.5)

In [210]:
elastic_net_model

ElasticNet(alpha=1)

In [211]:
elastic_net_model.fit(x_train,y_train)

ElasticNet(alpha=1)

In [212]:
for i, col_name in enumerate(x_train.columns):
    print(f"The coefficent for {col_name} is {elastic_net_model.coef_[i]}")

The coefficent for cylinders is -0.0
The coefficent for displacement is 0.0058888699536675465
The coefficent for horsepower is -0.012403874933570107
The coefficent for weight is -0.00693455051625763
The coefficent for acceleration is 0.0
The coefficent for model_year is 0.7133150744603873
The coefficent for origin is 0.0

In [213]:
y_pred_elastic_net=elastic_net_model.predict(x_test)
r2_elastic_net=r2_score(y_test, y_pred_elastic_net)
print(f"The r square of lasso regression {r2_elastic_net}")

The r square of lasso regression 0.8284840073256804

### Regularisation With crossvalidation

In [214]:
from sklearn.linear_model import LassoCV
lasso_cv=LassoCV(cv=5, verbose=2)

In [215]:
lasso_cv

LassoCV(cv=5, verbose=2)

In [216]:
lasso_cv.fit(x_train, y_train)

Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100
Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100
Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100
Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100
Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100

LassoCV(cv=5, verbose=2)

In [217]:
y_pred=lasso_cv.predict(x_test)
score=r2_score(y_test,y_pred)
print(f"The r square of Lasso CV {score}")

The r square of Lasso CV 0.808280598384475

In [218]:
from sklearn.linear_model import RidgeCV
ridgecv=RidgeCV(cv=5)
ridgecv.fit(x_train, y_train)

RidgeCV(cv=5)

In [219]:
y_pred=ridgecv.predict(x_test)
r2_score(y_test, y_pred)

0.8354145247502051

In [220]:
ridgecv.get_params()

{'alpha_per_target': False,
 'alphas': (0.1, 1.0, 10.0),
 'cv': 5,
 'fit_intercept': True,
 'gcv_mode': None,
 'scoring': None,
 'store_cv_results': None,
 'store_cv_values': 'deprecated'}

In [221]:
from sklearn.linear_model import ElasticNetCV

In [222]:
elastic_cv=ElasticNetCV(cv=5)
elastic_cv.fit(x_train, y_train)

ElasticNetCV(cv=5)

In [223]:
y_pred=elastic_cv.predict(x_test)
r2_score(y_test, y_pred)

0.792863401804916

# 2 - Hyperparmeter tuning

In [224]:
# Cv with hyperparameter tuning

In [225]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.linear_model import Lasso, Ridge

In [226]:
# Define the model
lasso=Lasso()

In [227]:
lasso

Lasso()

In [228]:
# grid seach cv>> Dictionary with parameter names(str)

param_grid={'alpha':[0.001,0.01,0.1,1,10,100]}
param_grid

{'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}

In [229]:
grid_search=GridSearchCV(estimator=lasso, param_grid=param_grid, cv=5, scoring='r2', verbose=2)
grid_search

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}, scoring='r2',
             verbose=2)

In [230]:
grid_search.fit(x_train,y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}, scoring='r2',
             verbose=2)

In [231]:
grid_search.best_params_

{'alpha': 0.1}

In [232]:
grid_search.best_params_['alpha']

0.1

In [233]:
grid_search.best_score_

np.float64(0.7964209726696481)

In [234]:
grid_search.best_estimator_

Lasso(alpha=0.1)

In [235]:
y_pred=grid_search.best_estimator_.predict(x_test)
r2_score(y_test,y_pred)

0.8345318641232304

In [236]:
## Randomized search cv for lasso

In [237]:
lasso=Lasso()
param_distributions={'alpha':[0.001,0.01,0.1,10,1,100]}
random_search_lasso=RandomizedSearchCV(estimator=lasso, param_distributions=param_distributions,n_iter=3, cv=5,scoring='r2',verbose=2)
random_search_lasso

RandomizedSearchCV(cv=5, estimator=Lasso(), n_iter=3,
                   param_distributions={'alpha': [0.001, 0.01, 0.1, 10, 1,
                                                  100]},
                   scoring='r2', verbose=2)

In [238]:
random_search_lasso.fit(x_train,y_train)
# due to n_iter parameters in each cross validation random 3 parameters are selected

Fitting 5 folds for each of 3 candidates, totalling 15 fits
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s

RandomizedSearchCV(cv=5, estimator=Lasso(), n_iter=3,
                   param_distributions={'alpha': [0.001, 0.01, 0.1, 10, 1,
                                                  100]},
                   scoring='r2', verbose=2)

In [239]:
random_search_lasso.best_estimator_

Lasso(alpha=0.1)

In [240]:
random_search_lasso.best_score_

np.float64(0.7964209726696481)

In [241]:
y_pred=random_search_lasso.best_estimator_.predict(x_test)
r2_score(y_test,y_pred)

0.8345318641232304

In [242]:
# Ridge Grid Search CV
ridge=Ridge()
param_grid={'alpha':[0.001,0.01,0.1,1,10,100]}
ridge=GridSearchCV(estimator=ridge,param_grid=param_grid, cv=5, scoring='r2',verbose=2)
ridge.fit(x_train, y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}, scoring='r2',
             verbose=2)

In [243]:
ridge.best_params_

{'alpha': 10}

In [244]:
ridge.best_estimator_

Ridge(alpha=10)

In [246]:
y_pred=ridge.best_estimator_.predict(x_test)
r2_score(y_test, y_pred)

0.8354145247502051

In [247]:
# Ridge Randomazied search cv
ridge=Ridge()
param_distributions={'alpha':[0.001,0.01,0.1,1,10,100]}
ridge=RandomizedSearchCV(estimator=ridge,param_distributions=param_distributions,n_iter=2, cv=5, scoring='r2',verbose=2)
ridge.fit(x_train, y_train)
print(ridge.best_params_)
print(ridge.best_estimator_)
y_pred=ridge.best_estimator_.predict(x_test)
print(r2_score(y_test, y_pred))

Fitting 5 folds for each of 2 candidates, totalling 10 fits
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
{'alpha': 0.1}
Ridge(alpha=0.1)
0.8348084889168355

### Elastic net

In [250]:
# Elastic net 
# grid seach cv

model=ElasticNet()
param_grid={'alpha':[0.001,0.01,0.1,1,10,100],
           'l1_ratio':[0.1,0.4,0.9]}
model=GridSearchCV(estimator=model,param_grid=param_grid, cv=5, scoring='r2',verbose=2)
model.fit(x_train, y_train)
print(model.best_params_)
print(model.best_estimator_)
y_pred=model.best_estimator_.predict(x_test)
print(r2_score(y_test, y_pred))

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
{'alpha': 0.1, 'l1_ratio': 0.9}
ElasticNet(alpha=0.1, l1_ratio=0.9)
0.8345726087080975

In [251]:
model=ElasticNet()
param_distributions={'alpha':[0.001,0.01,0.1,1,10,100],
                    'l1_ratio':[0.1,0.4,0.9]}
model=RandomizedSearchCV(estimator=model,param_distributions=param_distributions,n_iter=2, cv=5, scoring='r2',verbose=2)
model.fit(x_train, y_train)
print(model.best_params_)
print(model.best_estimator_)
y_pred=model.best_estimator_.predict(x_test)
print(r2_score(y_test, y_pred))

Fitting 5 folds for each of 2 candidates, totalling 10 fits
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
{'l1_ratio': 0.9, 'alpha': 0.01}
ElasticNet(alpha=0.01, l1_ratio=0.9)
0.8348955636587218